// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: harnesses.sql

package dbgen

import (
	"context"
)

const createHarness = `-- name: CreateHarness :one
INSERT INTO harnesses (name, description, base_url, created_at, updated_at)
VALUES (?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, name, description, base_url, created_at, updated_at
`

type CreateHarnessParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	BaseUrl     string `json:"base_url"`
}

func (q *Queries) CreateHarness(ctx context.Context, arg CreateHarnessParams) (Harness, error) {
	row := q.db.QueryRowContext(ctx, createHarness, arg.Name, arg.Description, arg.BaseUrl)
	var i Harness
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.BaseUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteHarness = `-- name: DeleteHarness :exec
DELETE FROM harnesses WHERE id = ?
`

func (q *Queries) DeleteHarness(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteHarness, id)
	return err
}

const getHarness = `-- name: GetHarness :one
SELECT id, name, description, base_url, created_at, updated_at FROM harnesses WHERE id = ?
`

func (q *Queries) GetHarness(ctx context.Context, id int64) (Harness, error) {
	row := q.db.QueryRowContext(ctx, getHarness, id)
	var i Harness
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.BaseUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listHarnesses = `-- name: ListHarnesses :many
SELECT id, name, description, base_url, created_at, updated_at FROM harnesses ORDER BY updated_at DESC
`

func (q *Queries) ListHarnesses(ctx context.Context) ([]Harness, error) {
	rows, err := q.db.QueryContext(ctx, listHarnesses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Harness{}
	for rows.Next() {
		var i Harness
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.BaseUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHarness = `-- name: UpdateHarness :one
UPDATE harnesses SET name = ?, description = ?, base_url = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, description, base_url, created_at, updated_at
`

type UpdateHarnessParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	BaseUrl     string `json:"base_url"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateHarness(ctx context.Context, arg UpdateHarnessParams) (Harness, error) {
	row := q.db.QueryRowContext(ctx, updateHarness,
		arg.Name,
		arg.Description,
		arg.BaseUrl,
		arg.ID,
	)
	var i Harness
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.BaseUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
