// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: loops.sql

package dbgen

import (
	"context"
)

const countLoops = `-- name: CountLoops :one
SELECT COUNT(*) FROM loops WHERE harness_id = ?
`

func (q *Queries) CountLoops(ctx context.Context, harnessID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLoops, harnessID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLoop = `-- name: CreateLoop :one
INSERT INTO loops (harness_id, name, sort_order, method, path, headers_json, body, expected_status, expected_body_contains, extract_json_path, extract_variable, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, harness_id, name, sort_order, method, path, headers_json, body, expected_status, expected_body_contains, extract_json_path, extract_variable, created_at, updated_at
`

type CreateLoopParams struct {
	HarnessID            int64  `json:"harness_id"`
	Name                 string `json:"name"`
	SortOrder            int64  `json:"sort_order"`
	Method               string `json:"method"`
	Path                 string `json:"path"`
	HeadersJson          string `json:"headers_json"`
	Body                 string `json:"body"`
	ExpectedStatus       int64  `json:"expected_status"`
	ExpectedBodyContains string `json:"expected_body_contains"`
	ExtractJsonPath      string `json:"extract_json_path"`
	ExtractVariable      string `json:"extract_variable"`
}

func (q *Queries) CreateLoop(ctx context.Context, arg CreateLoopParams) (Loop, error) {
	row := q.db.QueryRowContext(ctx, createLoop,
		arg.HarnessID,
		arg.Name,
		arg.SortOrder,
		arg.Method,
		arg.Path,
		arg.HeadersJson,
		arg.Body,
		arg.ExpectedStatus,
		arg.ExpectedBodyContains,
		arg.ExtractJsonPath,
		arg.ExtractVariable,
	)
	var i Loop
	err := row.Scan(
		&i.ID,
		&i.HarnessID,
		&i.Name,
		&i.SortOrder,
		&i.Method,
		&i.Path,
		&i.HeadersJson,
		&i.Body,
		&i.ExpectedStatus,
		&i.ExpectedBodyContains,
		&i.ExtractJsonPath,
		&i.ExtractVariable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLoop = `-- name: DeleteLoop :exec
DELETE FROM loops WHERE id = ?
`

func (q *Queries) DeleteLoop(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteLoop, id)
	return err
}

const getLoop = `-- name: GetLoop :one
SELECT id, harness_id, name, sort_order, method, path, headers_json, body, expected_status, expected_body_contains, extract_json_path, extract_variable, created_at, updated_at FROM loops WHERE id = ?
`

func (q *Queries) GetLoop(ctx context.Context, id int64) (Loop, error) {
	row := q.db.QueryRowContext(ctx, getLoop, id)
	var i Loop
	err := row.Scan(
		&i.ID,
		&i.HarnessID,
		&i.Name,
		&i.SortOrder,
		&i.Method,
		&i.Path,
		&i.HeadersJson,
		&i.Body,
		&i.ExpectedStatus,
		&i.ExpectedBodyContains,
		&i.ExtractJsonPath,
		&i.ExtractVariable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLoops = `-- name: ListLoops :many
SELECT id, harness_id, name, sort_order, method, path, headers_json, body, expected_status, expected_body_contains, extract_json_path, extract_variable, created_at, updated_at FROM loops WHERE harness_id = ? ORDER BY sort_order ASC, id ASC
`

func (q *Queries) ListLoops(ctx context.Context, harnessID int64) ([]Loop, error) {
	rows, err := q.db.QueryContext(ctx, listLoops, harnessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Loop{}
	for rows.Next() {
		var i Loop
		if err := rows.Scan(
			&i.ID,
			&i.HarnessID,
			&i.Name,
			&i.SortOrder,
			&i.Method,
			&i.Path,
			&i.HeadersJson,
			&i.Body,
			&i.ExpectedStatus,
			&i.ExpectedBodyContains,
			&i.ExtractJsonPath,
			&i.ExtractVariable,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLoop = `-- name: UpdateLoop :one
UPDATE loops SET name = ?, sort_order = ?, method = ?, path = ?, headers_json = ?, body = ?, expected_status = ?, expected_body_contains = ?, extract_json_path = ?, extract_variable = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, harness_id, name, sort_order, method, path, headers_json, body, expected_status, expected_body_contains, extract_json_path, extract_variable, created_at, updated_at
`

type UpdateLoopParams struct {
	Name                 string `json:"name"`
	SortOrder            int64  `json:"sort_order"`
	Method               string `json:"method"`
	Path                 string `json:"path"`
	HeadersJson          string `json:"headers_json"`
	Body                 string `json:"body"`
	ExpectedStatus       int64  `json:"expected_status"`
	ExpectedBodyContains string `json:"expected_body_contains"`
	ExtractJsonPath      string `json:"extract_json_path"`
	ExtractVariable      string `json:"extract_variable"`
	ID                   int64  `json:"id"`
}

func (q *Queries) UpdateLoop(ctx context.Context, arg UpdateLoopParams) (Loop, error) {
	row := q.db.QueryRowContext(ctx, updateLoop,
		arg.Name,
		arg.SortOrder,
		arg.Method,
		arg.Path,
		arg.HeadersJson,
		arg.Body,
		arg.ExpectedStatus,
		arg.ExpectedBodyContains,
		arg.ExtractJsonPath,
		arg.ExtractVariable,
		arg.ID,
	)
	var i Loop
	err := row.Scan(
		&i.ID,
		&i.HarnessID,
		&i.Name,
		&i.SortOrder,
		&i.Method,
		&i.Path,
		&i.HeadersJson,
		&i.Body,
		&i.ExpectedStatus,
		&i.ExpectedBodyContains,
		&i.ExtractJsonPath,
		&i.ExtractVariable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
