// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"
)

type Harness struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	BaseUrl     string    `json:"base_url"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Loop struct {
	ID                   int64     `json:"id"`
	HarnessID            int64     `json:"harness_id"`
	Name                 string    `json:"name"`
	SortOrder            int64     `json:"sort_order"`
	Method               string    `json:"method"`
	Path                 string    `json:"path"`
	HeadersJson          string    `json:"headers_json"`
	Body                 string    `json:"body"`
	ExpectedStatus       int64     `json:"expected_status"`
	ExpectedBodyContains string    `json:"expected_body_contains"`
	ExtractJsonPath      string    `json:"extract_json_path"`
	ExtractVariable      string    `json:"extract_variable"`
	CreatedAt            time.Time `json:"created_at"`
	UpdatedAt            time.Time `json:"updated_at"`
}

type Migration struct {
	MigrationNumber int64     `json:"migration_number"`
	MigrationName   string    `json:"migration_name"`
	ExecutedAt      time.Time `json:"executed_at"`
}

type Run struct {
	ID         int64      `json:"id"`
	HarnessID  int64      `json:"harness_id"`
	Status     string     `json:"status"`
	StartedAt  *time.Time `json:"started_at"`
	FinishedAt *time.Time `json:"finished_at"`
	CreatedAt  time.Time  `json:"created_at"`
}

type RunVariable struct {
	ID    int64  `json:"id"`
	RunID int64  `json:"run_id"`
	Name  string `json:"name"`
	Value string `json:"value"`
}

type StepResult struct {
	ID             int64     `json:"id"`
	RunID          int64     `json:"run_id"`
	LoopID         int64     `json:"loop_id"`
	Status         string    `json:"status"`
	ActualStatus   *int64    `json:"actual_status"`
	ActualBody     string    `json:"actual_body"`
	ExtractedValue string    `json:"extracted_value"`
	ErrorMessage   string    `json:"error_message"`
	DurationMs     int64     `json:"duration_ms"`
	CreatedAt      time.Time `json:"created_at"`
}

type Visitor struct {
	ID        string    `json:"id"`
	ViewCount int64     `json:"view_count"`
	CreatedAt time.Time `json:"created_at"`
	LastSeen  time.Time `json:"last_seen"`
}
