// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: runs.sql

package dbgen

import (
	"context"
	"time"
)

const countRunsByHarness = `-- name: CountRunsByHarness :one
SELECT COUNT(*) FROM runs WHERE harness_id = ?
`

func (q *Queries) CountRunsByHarness(ctx context.Context, harnessID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRunsByHarness, harnessID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO runs (harness_id, status, started_at, created_at)
VALUES (?, 'running', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, harness_id, status, started_at, finished_at, created_at
`

func (q *Queries) CreateRun(ctx context.Context, harnessID int64) (Run, error) {
	row := q.db.QueryRowContext(ctx, createRun, harnessID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.HarnessID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createStepResult = `-- name: CreateStepResult :one
INSERT INTO step_results (run_id, loop_id, status, actual_status, actual_body, extracted_value, error_message, duration_ms, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
RETURNING id, run_id, loop_id, status, actual_status, actual_body, extracted_value, error_message, duration_ms, created_at
`

type CreateStepResultParams struct {
	RunID          int64  `json:"run_id"`
	LoopID         int64  `json:"loop_id"`
	Status         string `json:"status"`
	ActualStatus   *int64 `json:"actual_status"`
	ActualBody     string `json:"actual_body"`
	ExtractedValue string `json:"extracted_value"`
	ErrorMessage   string `json:"error_message"`
	DurationMs     int64  `json:"duration_ms"`
}

func (q *Queries) CreateStepResult(ctx context.Context, arg CreateStepResultParams) (StepResult, error) {
	row := q.db.QueryRowContext(ctx, createStepResult,
		arg.RunID,
		arg.LoopID,
		arg.Status,
		arg.ActualStatus,
		arg.ActualBody,
		arg.ExtractedValue,
		arg.ErrorMessage,
		arg.DurationMs,
	)
	var i StepResult
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.LoopID,
		&i.Status,
		&i.ActualStatus,
		&i.ActualBody,
		&i.ExtractedValue,
		&i.ErrorMessage,
		&i.DurationMs,
		&i.CreatedAt,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, harness_id, status, started_at, finished_at, created_at FROM runs WHERE id = ?
`

func (q *Queries) GetRun(ctx context.Context, id int64) (Run, error) {
	row := q.db.QueryRowContext(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.HarnessID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRunVariables = `-- name: GetRunVariables :many
SELECT id, run_id, name, value FROM run_variables WHERE run_id = ?
`

func (q *Queries) GetRunVariables(ctx context.Context, runID int64) ([]RunVariable, error) {
	rows, err := q.db.QueryContext(ctx, getRunVariables, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunVariable{}
	for rows.Next() {
		var i RunVariable
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Name,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lastRunByHarness = `-- name: LastRunByHarness :one
SELECT id, harness_id, status, started_at, finished_at, created_at FROM runs WHERE harness_id = ? ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) LastRunByHarness(ctx context.Context, harnessID int64) (Run, error) {
	row := q.db.QueryRowContext(ctx, lastRunByHarness, harnessID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.HarnessID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listRuns = `-- name: ListRuns :many
SELECT id, harness_id, status, started_at, finished_at, created_at FROM runs WHERE harness_id = ? ORDER BY created_at DESC LIMIT 50
`

func (q *Queries) ListRuns(ctx context.Context, harnessID int64) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, listRuns, harnessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Run{}
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.HarnessID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStepResults = `-- name: ListStepResults :many
SELECT sr.id, sr.run_id, sr.loop_id, sr.status, sr.actual_status, sr.actual_body, sr.extracted_value, sr.error_message, sr.duration_ms, sr.created_at, l.name as loop_name, l.method, l.path, l.expected_status, l.expected_body_contains
FROM step_results sr
JOIN loops l ON sr.loop_id = l.id
WHERE sr.run_id = ?
ORDER BY sr.id ASC
`

type ListStepResultsRow struct {
	ID                   int64     `json:"id"`
	RunID                int64     `json:"run_id"`
	LoopID               int64     `json:"loop_id"`
	Status               string    `json:"status"`
	ActualStatus         *int64    `json:"actual_status"`
	ActualBody           string    `json:"actual_body"`
	ExtractedValue       string    `json:"extracted_value"`
	ErrorMessage         string    `json:"error_message"`
	DurationMs           int64     `json:"duration_ms"`
	CreatedAt            time.Time `json:"created_at"`
	LoopName             string    `json:"loop_name"`
	Method               string    `json:"method"`
	Path                 string    `json:"path"`
	ExpectedStatus       int64     `json:"expected_status"`
	ExpectedBodyContains string    `json:"expected_body_contains"`
}

func (q *Queries) ListStepResults(ctx context.Context, runID int64) ([]ListStepResultsRow, error) {
	rows, err := q.db.QueryContext(ctx, listStepResults, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStepResultsRow{}
	for rows.Next() {
		var i ListStepResultsRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.LoopID,
			&i.Status,
			&i.ActualStatus,
			&i.ActualBody,
			&i.ExtractedValue,
			&i.ErrorMessage,
			&i.DurationMs,
			&i.CreatedAt,
			&i.LoopName,
			&i.Method,
			&i.Path,
			&i.ExpectedStatus,
			&i.ExpectedBodyContains,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRunStatus = `-- name: UpdateRunStatus :exec
UPDATE runs SET status = ?, finished_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateRunStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateRunStatus(ctx context.Context, arg UpdateRunStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateRunStatus, arg.Status, arg.ID)
	return err
}

const upsertRunVariable = `-- name: UpsertRunVariable :exec
INSERT INTO run_variables (run_id, name, value)
VALUES (?, ?, ?)
ON CONFLICT(run_id, name) DO UPDATE SET value = excluded.value
`

type UpsertRunVariableParams struct {
	RunID int64  `json:"run_id"`
	Name  string `json:"name"`
	Value string `json:"value"`
}

func (q *Queries) UpsertRunVariable(ctx context.Context, arg UpsertRunVariableParams) error {
	_, err := q.db.ExecContext(ctx, upsertRunVariable, arg.RunID, arg.Name, arg.Value)
	return err
}
